# Generated by Django 4.0.5 on 2022-06-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choises_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Chois',
        ),
    ]
