# Generated by Django 4.0.5 on 2022-06-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choise_chois'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chois',
            new_name='Choise',
        ),
    ]
