# Generated by Django 4.0.5 on 2022-06-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_chois_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choises_text',
            new_name='choices_text',
        ),
    ]
