# Generated by Django 4.0.5 on 2022-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_choise_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.IntegerField(default=0),
        ),
    ]
