# Generated by Django 4.0.5 on 2022-06-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
